/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Fonction.Fonction;
import Mapping.Employer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ITU
 */
public class ListEmp extends javax.swing.JFrame {

    /**
     * Creates new form ListEmp
     */
    DefaultTableModel model;
    Object[] idemployer;
    Object[] idsalire;
    Object[] idhoraire;
    Object[] idposte;
    Object[] nomemployer;
    Object[] cinemployer;
    Object[] sexeemployer;
    
    public ListEmp() {
        initComponents();
        model = new DefaultTableModel();
        
        Fonction f = new Fonction();
        int size = f.countEmployer();
        Employer[] emp = f.selectEmployer();
        idemployer = new Object[size];
        idsalire = new Object[size];
        idhoraire = new Object[size];
        idposte = new Object[size];
        nomemployer = new Object[size];
        cinemployer = new Object[size];
        sexeemployer = new Object[size];
        
        for(int i=0;i<size;i++){
            idemployer[i] = (Object)emp[i].getIdemployer();
            idsalire[i] = (Object)emp[i].getIdsalire();
            idhoraire[i] = (Object)emp[i].getIdhoraire();
            idposte[i] = (Object)emp[i].getIdposte();
            nomemployer[i] = (Object)emp[i].getNomemployer();
            cinemployer[i] = (Object)emp[i].getCinemployer();
            //sexeemployer[i] = (Object)emp[i].get();
        }
        
        jTable1.setModel(model);
        model.addColumn("Id Employer",idemployer);
        model.addColumn("Id Salaire",idsalire);
        model.addColumn("Id Horaire",idhoraire);
        model.addColumn("Id Poste",idposte);
        model.addColumn("Nom",nomemployer);
        model.addColumn("Cin",cinemployer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
